spring.application.name=cyber-threat-alert-portal

spring.datasource.url=jdbc:mysql://localhost:3306/location_alert_db
spring.datasource.username=root
spring.datasource.password=pratik

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false
